### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by suuuehgi** [hickford/primesieve-python#20] opened 2018-03-14 15:23 UTC
Python 3.6.4
```
>>> from primesieve import *
>>> primes(40)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'primes' is not defined
```
The same for all examples. :/

**Comment by smoneck** [comment] 2018-03-14 15:24
As well as
```
>>> from primesieve.numpy import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'primesieve.numpy'
```

**Comment by kimwalisch** [comment] 2018-03-14 16:49
Have you previously installed primesieve using pip3?

```
pip3 install primesieve
python3
>>> from primesieve import *
>>> primes(40)
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37]
```

Could you also let me know which operating system you are using so that I can try to reproduce your bug?

**Comment by kimwalisch** [comment] 2018-03-14 17:00
If your operating system is not Windows you need to have a C++ compiler installed before installing primesieve using pip.

To install a C++ compiler on Linux use e.g.:

```
sudo apt install gcc-g++
```

To install a C++ compiler on macOS you should read the [prerequisites](https://github.com/hickford/primesieve-python#prerequisites).

**Comment by smoneck** [comment] 2018-03-14 22:43
Thank you for the fast answer! It is the first time installing `primesieve`.

```
> uname -a
Linux hostname 4.15.8-1-ARCH #1 SMP PREEMPT Sat Mar 10 00:00:33 UTC 2018 x86_64 GNU/Linux
```

```
> sudo pip3 install primesieve
Requirement already satisfied: primesieve in /usr/lib/python3.6/site-packages

> sudo pip3 install --upgrade primesieve
Requirement already up-to-date: primesieve in /usr/lib/python3.6/site-packages

> sudo pip3 uninstall primesieve
Uninstalling primesieve-1.3.0:
  /usr/lib/python3.6/site-packages/primesieve-1.3.0-py3.6.egg-info
  /usr/lib/python3.6/site-packages/primesieve/__init__.py
  /usr/lib/python3.6/site-packages/primesieve/__pycache__/__init__.cpython-36.pyc
  /usr/lib/python3.6/site-packages/primesieve/_primesieve.cpython-36m-x86_64-linux-gnu.so
  /usr/lib/python3.6/site-packages/primesieve/numpy/__init__.py
  /usr/lib/python3.6/site-packages/primesieve/numpy/__pycache__/__init__.cpython-36.pyc
  /usr/lib/python3.6/site-packages/primesieve/numpy/_numpy.cpython-36m-x86_64-linux-gnu.so
Proceed (y/n)? y
  Successfully uninstalled primesieve-1.3.0

> sudo pip3 install --no-cache-dir primesieve
Collecting primesieve
  Downloading primesieve-1.3.0.tar.gz (234kB)
    100% |################################| 235kB 8.1MB/s 
Installing collected packages: primesieve
  Running setup.py install for primesieve ... done
Successfully installed primesieve-1.3.0
```
```
> python3
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from primesieve import *
>>> primes(40)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'primes' is not defined
```

**Comment by smoneck** [comment] 2018-03-14 22:47
P.s.: Maybe that helps

```
> python3       
Python 3.6.4 (default, Jan  5 2018, 02:35:40) 
[GCC 7.2.1 20171224] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import primesieve         
>>> dir(primesieve)
['__doc__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```

**Comment by smoneck** [comment] 2018-03-14 23:47
P.p.s.: `py3status` crashes when `primesieve` is installed.

```
M<C3><A4>r 15 00:42:01 hostname slim[5629]: [../i3-4.14.1/../i3-4.14.1/i3bar/src/child.c:464] ERROR: Child (pid: 7538) unexpectedly exited with >
M<C3><A4>r 15 00:42:01 hostname slim[5629]: [../i3-4.14.1/../i3-4.14.1/i3bar/src/child.c:340] ERROR: stdin: received EOF
M<C3><A4>r 15 00:42:01 hostname slim[5629]: PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.6/site-packages/primesieve-1.3.0-py>
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     if len(os.listdir(path)) == 0:
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2133, in distributions_fro>
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     for dist in factory(fullpath):
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2071, in find_on_path
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     for dist in find_distributions(entry, True):
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 721, in add_entry
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     self.add_entry(entry)
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 665, in __init__
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     ws = cls()
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 672, in _build_master
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     working_set = WorkingSet._build_master()
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_maste>
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     f(*args, **kwargs)
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     @_call_aside
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3195, in <module>
M<C3><A4>r 15 00:42:01 hostname slim[5629]:     from pkg_resources import load_entry_point
M<C3><A4>r 15 00:42:01 hostname slim[5629]:   File "/usr/bin/py3status", line 6, in <module>
M<C3><A4>r 15 00:42:01 hostname slim[5629]: Traceback (most recent call last):
```

**Comment by kimwalisch** [comment] 2018-06-24 09:20
Hi,

I have tried to reproduce your bug. A few weeks ago I tried to install Arch Linux but I failed because it is simply too complicated to install Arch Linux! So today I installed Manjaro Linux x86_64 (which is based on Arch Linux) and primesieve-python works without any issues there:

```
$ sudo pip install primesieve 
...
Collecting primesieve
  Downloading https://files.pythonhosted.org/packages/fa/b0/195b9afe71dd221918577635084c339ada2dce8ffb9ba1d5fdfafbaddaa6/primesieve-1.4.3.tar.gz (198kB)
    100% |████████████████████████████████| 204kB 2.6MB/s 
Installing collected packages: primesieve
  Running setup.py install for primesieve ... done
Successfully installed primesieve-1.4.3
You are using pip version 9.0.1, however version 10.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[kim@kim-pc ~]$ python
Python 3.6.5 (default, Apr 14 2018, 13:17:30) 
[GCC 7.3.1 20180406] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from primesieve import *
>>> primes(1000)
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233, 239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311, 313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389, 397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463, 467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563, 569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641, 643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727, 733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821, 823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907, 911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997]
>>> count_primes(1e11)
4118054813
```

As I was unable to reproduce your bug I will close this issue for now.

**Closed by kimwalisch** 2018-06-24 09:20 UTC
